//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLietKeCP_BoSung
    {
        public int IDBoSung { get; set; }
        public Nullable<int> IDLoHang { get; set; }
        public Nullable<int> IDCP { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public string NguoiTao { get; set; }
    }
}
