//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangPhiDiDuong_ChiKhac_Temp
    {
        public int IDCT { get; set; }
        public Nullable<int> IDBangPhi { get; set; }
        public Nullable<double> SoTienChi { get; set; }
        public string NoiDungChi { get; set; }
    }
}
