//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDieuXe22
    {
        public int IDBangPhi { get; set; }
        public string MaDieuXe { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TuyenVC { get; set; }
        public Nullable<double> LaiXeThuCuoc { get; set; }
        public Nullable<double> TienAn { get; set; }
        public Nullable<double> TienVe { get; set; }
        public Nullable<double> QuaDem { get; set; }
        public Nullable<double> TienLuat { get; set; }
        public Nullable<double> LuongHangVe { get; set; }
        public Nullable<bool> DuyetChi { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiDuyet { get; set; }
        public string SoFile { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> ThoiGianDuyet { get; set; }
        public Nullable<double> DiemTraHang { get; set; }
        public string MaKhachHang { get; set; }
        public string LoaiXe_KH { get; set; }
        public string LoaiXe_NCC { get; set; }
        public Nullable<double> TTHQ { get; set; }
        public Nullable<double> CuocBan { get; set; }
        public Nullable<double> CuocMua { get; set; }
        public string MaNhaCungCap { get; set; }
        public string BienSoXe { get; set; }
        public string LaiXe { get; set; }
        public string DoiTru { get; set; }
        public Nullable<double> PhiDichVu_DoiTru { get; set; }
    }
}
