//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangTheoDoiNghiPhepNam
    {
        public int IDNghiPhep { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> CaNgay { get; set; }
        public Nullable<bool> Duyet { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> ThoiGianDuyet { get; set; }
    }
}
