//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangHoanUng
    {
        public int IDHoanUng { get; set; }
        public string SoFile { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<float> TamUng { get; set; }
        public Nullable<float> ChiPhi { get; set; }
        public Nullable<float> HoanLai { get; set; }
        public Nullable<System.DateTime> NgayHoanUng { get; set; }
    }
}
