//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLietKeCP
    {
        public int IDCP { get; set; }
        public Nullable<int> IDLoHang { get; set; }
        public Nullable<float> PhiDangKy { get; set; }
        public Nullable<System.DateTime> NgayTaoBangKe { get; set; }
        public string NguoiTaoBangKe { get; set; }
        public Nullable<bool> XacNhanHoanUng { get; set; }
        public Nullable<System.DateTime> NgayHoanUng { get; set; }
        public Nullable<bool> XacNhanHoangUngNhanVien { get; set; }
        public Nullable<System.DateTime> NgayHoanUngNhanVien { get; set; }
        public string MaNhanVien { get; set; }
        public string SoFile { get; set; }
        public Nullable<bool> Duyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public string LyDoDuyet { get; set; }
    }
}
