//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangPhoiNangHa
    {
        public int IDCP { get; set; }
        public Nullable<int> IDLoHang { get; set; }
        public Nullable<double> PhiDangKy { get; set; }
        public Nullable<System.DateTime> NgayTaoBangKe { get; set; }
        public string NguoiTaoBangKe { get; set; }
    }
}
