//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangPhiDiDuong22
    {
        public int IDBangPhi { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TuyenVC { get; set; }
        public Nullable<double> LaiXeThuCuoc { get; set; }
        public Nullable<double> TienAn { get; set; }
        public Nullable<double> TienVe { get; set; }
        public Nullable<double> QuaDem { get; set; }
        public Nullable<double> TienLuat { get; set; }
        public Nullable<double> LuongHangVe { get; set; }
        public Nullable<bool> DuyetChi { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiDuyet { get; set; }
        public string SoFile { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> ThoiGianDuyet { get; set; }
        public Nullable<double> DiemTraHang { get; set; }
        public string MaDieuXe { get; set; }
        public string PhanHoi { get; set; }
    }
}
