//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLietKeCP_ChiTiet
    {
        public int IDCPCT { get; set; }
        public string MaChiPhi_HQ { get; set; }
        public Nullable<double> SoTien_HQ { get; set; }
        public string MaChiHo { get; set; }
        public Nullable<double> SoTien_ChiHo { get; set; }
        public string GhiChu_HQ { get; set; }
        public string GhiChu_ChiHo { get; set; }
        public Nullable<int> IDLoHang { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<int> IDCP { get; set; }
        public string LinkTaiHoaDon { get; set; }
        public string MaTraCuu { get; set; }
    }
}
