//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangKePhiChiHo1
    {
        public int IDBangKePhiChiHo { get; set; }
        public string PhiChiHo { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<decimal> SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
    }
}
