//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacLoaiPhiChiHo
    {
        public int IDCacLoaiPhiChiHo { get; set; }
        public string Cược { get; set; }
        public string PhiCSHT { get; set; }
        public string PhiLayLenh { get; set; }
        public string PhiNangCont { get; set; }
        public string PhiHaCont { get; set; }
        public string PhiRutRuot { get; set; }
        public string PhiDongHang { get; set; }
        public string Phiếu_tạm_thu { get; set; }
    }
}
