//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachKhachHang
    {
        public int ID { get; set; }
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string STK { get; set; }
        public Nullable<int> SoNgayDuocNo { get; set; }
        public Nullable<float> NoToiDa { get; set; }
        public Nullable<bool> LaNhaCungCap { get; set; }
        public string GhiChu { get; set; }
        public string TenVietTat { get; set; }
    }
}
