//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_CPHQ
    {
        public int ID { get; set; }
        public string MaChiPhi { get; set; }
        public string TenChiPhi { get; set; }
        public Nullable<float> SoTien { get; set; }
    }
}
