//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucNganHang
    {
        public int IDNganHang { get; set; }
        public string SoTK { get; set; }
        public string TenNganHang { get; set; }
        public string ChiNhanh { get; set; }
        public string ChuTaiKhoan { get; set; }
    }
}
