//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_PhiChiHo
    {
        public int ID { get; set; }
        public string MaChiHo { get; set; }
        public string TenChiHo { get; set; }
        public Nullable<float> SoTien { get; set; }
    }
}
