//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucThu
    {
        public int IDThu { get; set; }
        public string MaThu { get; set; }
        public string TenThu { get; set; }
        public string MaCha { get; set; }
    }
}
