//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauKy_Quy
    {
        public int IDQuyCongNo { get; set; }
        public string MaQuy { get; set; }
        public string SoTK { get; set; }
        public string TenNganHang { get; set; }
        public Nullable<double> SDDK { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string HinhThucTT { get; set; }
    }
}
