//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDebitChiTiet
    {
        public int IDDeBitCT { get; set; }
        public Nullable<int> IDDeBit { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> LaPhiChiHo { get; set; }
        public string SoHoaDon { get; set; }
        public string DoiTru { get; set; }
        public Nullable<double> PhiDichVu_DoiTru { get; set; }
    }
}
