//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDebit
    {
        public int IDDeBit { get; set; }
        public int IDGia { get; set; }
        public Nullable<int> IDLoHang { get; set; }
        public string SoFile { get; set; }
        public Nullable<System.DateTime> ThoiGianLap { get; set; }
        public string NguoiLap { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
    }
}
