//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDebit_KoHoaDon_KH
    {
        public int IDDeBit { get; set; }
        public string MaDieuXe { get; set; }
        public string MaKhachHang { get; set; }
        public string LoaiXe_KH { get; set; }
        public string TuyenVC { get; set; }
        public Nullable<double> CuocMua { get; set; }
        public Nullable<double> CuocBan { get; set; }
        public Nullable<double> LaiXeThuCuoc { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> PhiCom { get; set; }
        public Nullable<double> DoanhThuThuan { get; set; }
        public string MaNhaCungCap { get; set; }
        public string SoHoaDon { get; set; }
        public string DoiTru { get; set; }
        public Nullable<double> PhiDichVu_DoiTru { get; set; }
        public Nullable<double> PhiChiHo_DoiTru { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<bool> Chon { get; set; }
    }
}
