//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileGiaChiTiet
    {
        public int IDGiaCT { get; set; }
        public Nullable<int> IDGia { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> GiaMua { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> IDCP { get; set; }
        public string MaNhaCungCap { get; set; }
        public string DoiTru { get; set; }
        public Nullable<double> PhiChiHo_DoiTru { get; set; }
        public Nullable<System.DateTime> Tg { get; set; }
        public Nullable<bool> LinhVucKhac { get; set; }
    }
}
