//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaiBao_TSCD
    {
        public int IDKhauHao { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoChungTu { get; set; }
        public string MaTaiSan { get; set; }
        public string TenTaiSan { get; set; }
        public Nullable<double> GiaTri { get; set; }
        public Nullable<double> ThoiGianPhanBo { get; set; }
        public Nullable<double> GiaTriPhanBo { get; set; }
        public Nullable<double> KhauHaoLuyKe { get; set; }
        public Nullable<double> GiaTriConLai { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NguoiTao { get; set; }
    }
}
