//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vua45987_vudacoEntities : DbContext
    {
        public vua45987_vudacoEntities()
            : base("name=vua45987_vudacoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangDieuXe> BangDieuXe { get; set; }
        public virtual DbSet<BangDieuXe_ChiTiet> BangDieuXe_ChiTiet { get; set; }
        public virtual DbSet<BangHoanUng> BangHoanUng { get; set; }
        public virtual DbSet<BangKePhiChiHo1> BangKePhiChiHo1 { get; set; }
        public virtual DbSet<BangLietKeCP> BangLietKeCP { get; set; }
        public virtual DbSet<BangLietKeCP_BoSung> BangLietKeCP_BoSung { get; set; }
        public virtual DbSet<BangLietKeCP_ChiTiet> BangLietKeCP_ChiTiet { get; set; }
        public virtual DbSet<BangPhiDiDuong> BangPhiDiDuong { get; set; }
        public virtual DbSet<BangPhiDiDuong_ChiKhac> BangPhiDiDuong_ChiKhac { get; set; }
        public virtual DbSet<BangPhiDiDuong_ChiKhac_Temp> BangPhiDiDuong_ChiKhac_Temp { get; set; }
        public virtual DbSet<BangPhiDiDuong_Temp> BangPhiDiDuong_Temp { get; set; }
        public virtual DbSet<BangPhoiNangHa> BangPhoiNangHa { get; set; }
        public virtual DbSet<BangPhoiNangHa_ChiTiet> BangPhoiNangHa_ChiTiet { get; set; }
        public virtual DbSet<BangTheoDoiNghiPhepNam> BangTheoDoiNghiPhepNam { get; set; }
        public virtual DbSet<CacLoaiPhiChiHo> CacLoaiPhiChiHo { get; set; }
        public virtual DbSet<ChiKhac_Web_Temp> ChiKhac_Web_Temp { get; set; }
        public virtual DbSet<DanhMuc_CPHQ> DanhMuc_CPHQ { get; set; }
        public virtual DbSet<DanhMuc_PhiChiHo> DanhMuc_PhiChiHo { get; set; }
        public virtual DbSet<DanhMucNganHang> DanhMucNganHang { get; set; }
        public virtual DbSet<DanhMucQuy> DanhMucQuy { get; set; }
        public virtual DbSet<DanhMucThu> DanhMucThu { get; set; }
        public virtual DbSet<DanhSachChi> DanhSachChi { get; set; }
        public virtual DbSet<DanhSachChiPhiHaiQuan> DanhSachChiPhiHaiQuan { get; set; }
        public virtual DbSet<DanhSachKhachHang> DanhSachKhachHang { get; set; }
        public virtual DbSet<DanhSachNhaCungCap> DanhSachNhaCungCap { get; set; }
        public virtual DbSet<DanhSachTaiKhoan> DanhSachTaiKhoan { get; set; }
        public virtual DbSet<DanhSachXe> DanhSachXe { get; set; }
        public virtual DbSet<DauKy_Quy> DauKy_Quy { get; set; }
        public virtual DbSet<FileDebit> FileDebit { get; set; }
        public virtual DbSet<FileDebit_KoHoaDon_KH> FileDebit_KoHoaDon_KH { get; set; }
        public virtual DbSet<FileDebit_KoHoaDon_NCC> FileDebit_KoHoaDon_NCC { get; set; }
        public virtual DbSet<FileDebitChiTiet> FileDebitChiTiet { get; set; }
        public virtual DbSet<FileGia> FileGia { get; set; }
        public virtual DbSet<FileGiaChiTiet> FileGiaChiTiet { get; set; }
        public virtual DbSet<KhaiBao_TSCD> KhaiBao_TSCD { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NhanVien_PhuCap> NhanVien_PhuCap { get; set; }
        public virtual DbSet<PhanBo_KhauHao> PhanBo_KhauHao { get; set; }
        public virtual DbSet<PhanBo_KhauHao_DSXe> PhanBo_KhauHao_DSXe { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyen { get; set; }
        public virtual DbSet<PhieuBan> PhieuBan { get; set; }
        public virtual DbSet<PhieuBanCT> PhieuBanCT { get; set; }
        public virtual DbSet<PhieuChi> PhieuChi { get; set; }
        public virtual DbSet<PhieuChi_Con> PhieuChi_Con { get; set; }
        public virtual DbSet<PhieuChi_Con_CT> PhieuChi_Con_CT { get; set; }
        public virtual DbSet<PhieuChi_CT> PhieuChi_CT { get; set; }
        public virtual DbSet<PhieuChi_LaiXe> PhieuChi_LaiXe { get; set; }
        public virtual DbSet<PhieuChi_LaiXe_CT> PhieuChi_LaiXe_CT { get; set; }
        public virtual DbSet<PhieuChi_NCC> PhieuChi_NCC { get; set; }
        public virtual DbSet<PhieuChi_NCC_CT> PhieuChi_NCC_CT { get; set; }
        public virtual DbSet<PhieuChi_NganHang> PhieuChi_NganHang { get; set; }
        public virtual DbSet<PhieuChi_NoiBo> PhieuChi_NoiBo { get; set; }
        public virtual DbSet<PhieuChi_NoiBo_CT> PhieuChi_NoiBo_CT { get; set; }
        public virtual DbSet<PhieuCuoc> PhieuCuoc { get; set; }
        public virtual DbSet<PhieuMua> PhieuMua { get; set; }
        public virtual DbSet<PhieuMuaCT> PhieuMuaCT { get; set; }
        public virtual DbSet<PhieuTamThu> PhieuTamThu { get; set; }
        public virtual DbSet<PhieuThu> PhieuThu { get; set; }
        public virtual DbSet<PhieuThu_CT> PhieuThu_CT { get; set; }
        public virtual DbSet<PhieuThu_GiaoNhan> PhieuThu_GiaoNhan { get; set; }
        public virtual DbSet<PhieuThu_GiaoNhan_CT> PhieuThu_GiaoNhan_CT { get; set; }
        public virtual DbSet<PhieuThu_LaiXe> PhieuThu_LaiXe { get; set; }
        public virtual DbSet<PhieuThu_LaiXe_CT> PhieuThu_LaiXe_CT { get; set; }
        public virtual DbSet<PhieuThu_NoiBo> PhieuThu_NoiBo { get; set; }
        public virtual DbSet<PhieuThu_NoiBo_CT> PhieuThu_NoiBo_CT { get; set; }
        public virtual DbSet<PhongBan> PhongBan { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<ThongTinFile> ThongTinFile { get; set; }
        public virtual DbSet<ThongTinFile_NguoiGiaoNhan> ThongTinFile_NguoiGiaoNhan { get; set; }
        public virtual DbSet<BangDieuXe_Temp> BangDieuXe_Temp { get; set; }
        public virtual DbSet<BangDieuXe22> BangDieuXe22 { get; set; }
        public virtual DbSet<BangPhiDiDuong22> BangPhiDiDuong22 { get; set; }
    }
}
