//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int ID { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string CCCD { get; set; }
        public string GPLX { get; set; }
        public string MaPhongBan { get; set; }
        public Nullable<double> LuongCoDinh { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<bool> NCCNgoai { get; set; }
    }
}
