//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanBo_KhauHao_DSXe
    {
        public int IDCT { get; set; }
        public Nullable<int> IDPhanBo { get; set; }
        public string BienSoXe { get; set; }
    }
}
