//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int idPhanQuyen { get; set; }
        public string TaiKhoan { get; set; }
        public string Phân_Quyền { get; set; }
    }
}
