//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanBo_KhauHao
    {
        public int IDPhanBo { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoChungTu { get; set; }
        public string NoiDungPhanBo { get; set; }
        public Nullable<double> SoTienPhanBo { get; set; }
        public string NguoiTao { get; set; }
        public string MaTaiSan { get; set; }
        public string TenTaiSan { get; set; }
        public string BienSoXe { get; set; }
    }
}
