//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu_CT
    {
        public int IDCT { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<int> IDCP { get; set; }
        public string SoFile { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string DoiTuong { get; set; }
        public string MaDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> LaPhieuChiHo { get; set; }
        public Nullable<int> IDPhieuThu { get; set; }
        public string MaDieuXe { get; set; }
        public Nullable<double> Tien_DuyetUng { get; set; }
    }
}
