//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public int IDPhieuThu { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> NgayHachToan { get; set; }
        public string MaThu { get; set; }
        public string LyDoThu { get; set; }
        public string DienGiai { get; set; }
        public string SoHoaDon { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public string NguoiNhan { get; set; }
        public string MaQuy { get; set; }
        public string HinhThucTT { get; set; }
        public string SoTK { get; set; }
        public string TenNganHang { get; set; }
        public string ChiNhanh { get; set; }
        public string ChuTaiKhoan { get; set; }
    }
}
