//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMua
    {
        public int IDPhieuMua { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string MaNhaCC { get; set; }
        public string MaNhanVien { get; set; }
        public string NguoiMuaHang { get; set; }
        public string MaChi { get; set; }
        public string MaChiCon { get; set; }
        public string DienGiai { get; set; }
        public string NguoiTao { get; set; }
    }
}
