//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBanCT
    {
        public int IDPhieuBanCT { get; set; }
        public Nullable<int> IDPhieuBan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ThueVAT { get; set; }
        public Nullable<double> ThanhTienVAT { get; set; }
        public string SoHoaDon { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<bool> LaChiPhiPhanBo { get; set; }
        public Nullable<bool> LaChiPhiQuanLy { get; set; }
    }
}
