//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTamThu
    {
        public int IDTamThu { get; set; }
        public string SoFile { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> TienCuoc { get; set; }
        public string NguoiGiaoNhan { get; set; }
        public string GhiChu { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<bool> DaXacNhan { get; set; }
        public Nullable<System.DateTime> ThoiGianXacNhan { get; set; }
        public string NguoiXacNhan { get; set; }
        public Nullable<int> IDCP { get; set; }
        public Nullable<bool> LaLKCP { get; set; }
    }
}
