//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi_NganHang
    {
        public int IDPhieuChiNganHang { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> NgayHachToan { get; set; }
        public string DienGiai { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string DoiTuong { get; set; }
        public string MaDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public string NguoiNhan { get; set; }
        public string DiaChi { get; set; }
        public string MaChi { get; set; }
        public string LyDoChi { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string SoHoaDon { get; set; }
        public string GhiChu { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public string MaQuy { get; set; }
        public string SoFile { get; set; }
        public string SoTK { get; set; }
        public string TenNganHang { get; set; }
        public string ChiNhanh { get; set; }
        public string ChuTaiKhoan { get; set; }
    }
}
