//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBan
    {
        public int IDPhieuBan { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string DoiTuong { get; set; }
        public string MaNhaCC { get; set; }
        public string MaNhanVien { get; set; }
        public string NguoiBanHang { get; set; }
        public string MaThu { get; set; }
        public string DienGiai { get; set; }
        public string NguoiTao { get; set; }
    }
}
