//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinFile
    {
        public int IDLoHang { get; set; }
        public string MaKhachHang { get; set; }
        public string SoFile { get; set; }
        public string SoToKhai { get; set; }
        public string SoBill { get; set; }
        public string SoLuong { get; set; }
        public string SoCont { get; set; }
        public string TenSales { get; set; }
        public string LoaiHang { get; set; }
        public string TinhChat { get; set; }
        public Nullable<int> SoLuongToKhai { get; set; }
        public string LoaiToKhai { get; set; }
        public string NghiepVu { get; set; }
        public string PhatSinh { get; set; }
        public string TaiKhoanThucHien { get; set; }
        public Nullable<System.DateTime> ThoiGianThucHien { get; set; }
        public string GhiChu { get; set; }
    }
}
