//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVudaco
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinFile_NguoiGiaoNhan
    {
        public int IDGiaoNhan { get; set; }
        public string SoFile { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<double> DuyetUng { get; set; }
    }
}
